FROM ubuntu
RUN apt-get update \
    && apt-get install -y software-properties-common
RUN add-apt-repository -y ppa:openjdk-r/ppa
RUN apt-get update -q
RUN apt install -y openjdk-11-jdk
RUN apt-get install -y maven
RUN apt install -y git
