FROM ubuntu
RUN apt-get update \
    && apt-get install -y software-properties-common
RUN add-apt-repository ppa:openjdk-r/ppa \
    && apt-get update -q \
    && apt install -y openjdk-11-jdk \
RUN apt-get install maven
RUN apt install -y git
